### ISSUE TITLE
Remove Auto Rename Uploaded File

### ISSUE THREAD

**Issue by rifal89** [khodakhah/nodcms#14]
Hey, your CMS is great, i enjoyed develop my project with this cms. I ready fix some modification for my purpose. Now, i have problem with auto rename file when upload file. How to remove this feature? I just want use real file name.

Oh, keep develop this CMS, i hope this CMS have cool features like wordpress. I like wordpress, easy to use but no with security and speed.

Thanks

**Comment by khodakhah** [comment]
Hi,
Thank you so much for your Issue.
From `/nodcms/controllers/Nodcms_general_admin.php` **line 868 and 833** remove `$config['encrypt_name'] = true;` or instead of that write `$config['encrypt_name'] = false;`

I'm so glad that you use NodCMS. I'm trying to improve it.
That's my pleasure that you like NodCMS.

**Comment by rifal89** [comment]
Ouw okay, it's what i want... Thanks

**Comment by khodakhah** [comment]
New version of NodCMS updated.
