### ISSUE TITLE
URL whitout lang prefix

### ISSUE THREAD

**Issue by allado** [khodakhah/nodcms#15]
Hi.

How can i modify url language to http://mydomain.com   instead http://mydomain.com/en  ... URL whitout lang prefix /en  or /de ?

The site have only one lang. !

**Comment by khodakhah** [comment]
Hi,

## change routes
You should at first change `config/routes.php` to remove all prefix.

For example:
`$route['extension_list'] = 'pages/extension_list/en';
$route['extension_list/([0-9]+)'] = 'pages/extension_list/en/$2';`
instead of
`$route['([a-z][a-z])/extension_list'] = 'pages/extension_list/$1';
$route['([a-z][a-z])/extension_list/([0-9]+)'] = 'pages/extension_list/$1/$2';`
For index page remove `$route['([a-z][a-z])'] = 'pages/index/$1';` from `config/routes.php` and change **default_controller** like `$route['default_controller'] = "pages/index/en";`

## change links
Then add below function to `controllers/Nodcms_general.php`
`function _output($output){
        echo str_replace(base_url().'/en',base_url(),$output);
    }`

**Comment by allado** [comment]
Ok... but.... I want remove prefix.. /en.... URL clean !..... whitout lang prefix 

How is it ?

**Comment by allado** [comment]
Hi probe it and... it does not work

**Comment by khodakhah** [comment]
With this way you can so easily remove the language prefix.
Try it:
Insert the below function in your `controllers/Nodcms_general.php`

> function _remap($method,$params){
>         $params = array_merge(array('en'),$params);
>         return call_user_func_array(array($this, $method), $params);
>     }
>     function _output($output){
>         echo str_replace(array(base_url().'en/',base_url().'en'),base_url(),$output);
>     }


Replace your variables in `config/routes.php` with below variables:

> $route['default_controller'] = "Nodcms_general/index";
> $route['404_override'] = '';
> $route['page/([0-9]+)'] = 'Nodcms_general/page/$1';
> $route['extension/([0-9]+)'] = 'Nodcms_general/extension_detail/$1';
> $route['register'] = 'Nodcms_general/register';
> $route['login'] = 'Nodcms_general/login';
> $route['forget-password'] = 'Nodcms_general/forget_password';
> $route['login/([a-zA-Z0-9-]+)'] = 'Nodcms_general/login/$1';
> $route['active_account/([a-zA-Z0-9-]+)/([a-zA-Z0-9-]+)'] = 'Nodcms_general/reset_password/$1/$2';
> $route['reset-password/([a-zA-Z0-9-]+)/([a-zA-Z0-9-]+)'] = 'Nodcms_general/reset_password/$1/$2';
> $route['profile-password'] = 'Nodcms_general/profile_password';
> $route['contact'] = 'Nodcms_general/contact';
> $route['ajax/addcomment'] = 'Nodcms_general/extension_addcomment';
> $route['search'] = 'Nodcms_general/search';
> $route['new-feeds'] = 'Nodcms_general/rss';
> $route['sitemap.xml'] = 'Nodcms_general/sitemap_xml';
> $route['admin-sign']= "Nodcms_admin_sign/index";
> $route['admin-sign/login']= "Nodcms_admin_sign/login";
> $route['admin-sign/logout']= "Nodcms_admin_sign/logout";
> $route['admin']= "Nodcms_general_admin/index";
> $route['admin/(.*)']= "Nodcms_general_admin/$1";
> $route['translate_uri_dashes'] = FALSE;

**Comment by allado** [comment]
Ho yeah... good job.. im try it... Thats work !!!
