### ISSUE TITLE
There is a critical vulnerability in NodCMS

### ISSUE THREAD

**Issue by coalzhao** [khodakhah/nodcms#41]
I found a serious vulnerability in NodCMS.
if anyone could login in backend ,he can insert XSS code to execute，it would cause Information disclosure,Account stolen ,etc.
when login in backend,click settings ,then modify content in Address textarea into JavaScript code : 
![xss语句](https://user-images.githubusercontent.com/22334888/66637880-8b460b00-ec46-11e9-9155-4ba802f2ea76.png)
 and submit it. 
like this
![xss存储](https://user-images.githubusercontent.com/22334888/66637075-f4c51a00-ec44-11e9-8980-8bf898a4113c.png)
Then ,this string would be stored  in database.
When someone browse this website in frontend，this string of code will be execute .
example like this:
![xss验证](https://user-images.githubusercontent.com/22334888/66637176-1de5aa80-ec45-11e9-9a90-980b43f77b58.png)
This is a Stored XSS vulnerability, be kindly notified please.

**Comment by khodakhah** [comment]
Hi. Because this CMS created for only the webmaster with two types of administrations, I didn't spend a lot of time to verify all inputs in the admin side. Basically who has an admin password can do anything. So I don't think that it's a tragic problem for this type of CMS.
Anyway, thank you for your report. I'm working on the new version of NodCMS(develop branch). I'll check it on the new version as well.
Thanks
